version: "3.7"
services:
    web:
        build: .
        hostname: srvweb
        container_name: srvweb
        tty: true
        dns:
          - 8.8.8.8
          - 192.168.xx.30
        networks: 
            external:
            internal:
                ipv4_address: 192.168.xx.10
    db:
        build: .
        hostname: srvdb
        container_name: srvdb
        tty: true
        dns:
          - 8.8.8.8
          - 192.168.xx.30
        networks: 
            external:
            internal:
                ipv4_address: 192.168.xx.20
    dns:
        build: .
        restart: always
        hostname: srvdns
        container_name: srvdns
        tty: true
        dns:
          - 8.8.8.8
          - 192.168.xx.30
        networks: 
            external:
            internal:
                ipv4_address: 192.168.xx.30
networks: 
    internal: 
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.xx.0/24
        internal: true
    external:
